### ISSUE TITLE
Download robots.txt in SubdomainDataExtractor

### ISSUE THREAD

**Issue by eranzim** [eranzim/PT-tools#5]
In addition to all the other data that is collected - also bring robots.txt (if exists). Maybe also CrossDomain.xml.

**Comment by eranzim** [comment]
Examples of such files:
https://graph.facebook.com/robots.txt
http://download.macromedia.com/robots.txt
https://graph.facebook.com/crossdomain.xml
https://fpdownload.adobe.com/crossdomain.xml

**Comment by romainr88** [comment]
Hello,
I've pull the request for this issue
#7
